### PR TITLE
Add support for GHC 9.6.

### PR DESCRIPTION
**Pull request by athas**

### CODE REVIEW

**Comment by mainland** [comment]
Yes, eventually we will have to remove support for old GHC versions... but for now, I think we can add 9.6 to the list of supported versions without removing any others :)

**Comment by athas** [comment]
f86f0d3 contains everything that was necessary for GHC 9.6.

**Comment by athas** [comment]
Now all that is needed is a release on Hackage.  Shall I do that?

**Comment by mainland** [comment]
I went ahead and pushed a new release. Thanks for prodding me.

**Pull request closed without merging**
