### PR TITLE
Introduce expression/statement -level raw-string escapes

### PR DESCRIPTION
**Pull request by deepfire**

### CODE REVIEW

**Comment by mainland** [comment]
1. Please avoid whitespace-only changes :)
1. Why can't the $esc syntax be reused in an expression context?

**Comment by deepfire** [comment]
On point 1: do you mean the addition of cases in `qqExpE` / `qqExpP` in `Language/C/Quote/Base.hs`?  If so, would you prefer one-liners that would lead to unaligned cases?

On point 2: 
  - same antiquote name ->
  - same token ->
  - same non-terminal ->
  - will the grammar handle the ambiguity?  I chose the safer way, experimentation is needed here.

**Comment by mainland** [comment]
1. It looks like the patch added whitepsace in `Language/C/Parser/Parser.y`.
2. The $esc token only appears in a top-level definition context right now. Using it in an expression context shouldn't cause a conflict.

**Comment by deepfire** [comment]
On point 1: if you use github for review -- it seems like a bug in github -- line 3317 adds `getANTI_ESCEXP`, but also, notably, line 3317 isn't surrounded by whitespace, as github makes it appear.

**Comment by deepfire** [comment]
I have updated the branch -- now reusing `$exp`, as you suggested.

**Comment by deepfire** [comment]
Meanwhile, I have composed a little piece to get a picture of what adding an antiquoter entails:
```
  - Token definition
    - Lexer.x ::   "$esc:"     / { allowAnti } { lexAnti Tanti_esc }
    - Tokens.hs :: | Tanti_esc String
    - Tokens.hs :: show (Tanti_esc s)                  = showAnti "esc"  s
  - Token to non-terminal
    - Parser.y ::  getANTI_ESC         (L _ (T.Tanti_esc v))         = v
  - Non-terminal in AST
    - Parser.y ::  external_declaration :
			   ANTI_ESC { AntiEsc (getANTI_ESC $1) (srclocOf $1) }
  - Antiquote AST
    - Syntax.hs :: data Definition  =
			   AntiEsc    String    !SrcLoc
    - Pretty.hs :: ppr (AntiEsc v _)     =
			   pprAnti "esc" v
    - Syntax-instances.hs ::
		   instance Located Definition where
			   locOf (AntiEsc _ l) = locOf l
    - Syntax-instances.hs ::
		   instance Relocatable Definition where
			   reloc l (AntiEsc x0 _) = (AntiEsc x0 (fromLoc l))
  - Antiquote AST to non-antiquote AST
    - Base.hs ::   qqDefinitionE (C.AntiEsc v loc) =
			   Just [|C.EscDef $(antiVarE v) $(qqLocE loc)|]
    - Base.hs ::   qqDefinitionP (C.AntiEsc v _)   =
			   Just $ conP (mkName "C.EscDef") [antiVarP v, wildP]
```

**Comment by deepfire** [comment]
Added statement-level escape -- this time the grammar gave me a conflict, when I tried to reuse `esc`, so I punted to `escstm`.

**Comment by mainland** [comment]
Yes, expressions can appear in a statement context, so I would expect a conflict there. I don't see the added benefit of statement escapes---can you give an example where a statement escape is required?

**Comment by deepfire** [comment]
The test case I have added illuminates this.  But I'll show it here to streamline the discussion:
```
list_for_each_like (struct object *, obj, list, &list)
        if (obj_op (obj))
                return;
```
This can't be expressed by wrapping `list_for_each_like (struct object *, obj, list, &list)` into an expression -- because `if` is a statement.

**Comment by deepfire** [comment]
Just for the record -- the test case looks like this:
```
[citems|$escstm:rawstr if (1) return;|]
```
..which renders into:
```
{
    a rather random string
    if (1)
        return;
    
}

**Comment by deepfire** [comment]
@mainland, is there anything I can do on my side to move this ahead?

**Pull request merged**
