### PR TITLE
Lambda-expressions support as needed by accelerate-cuda

### PR DESCRIPTION
**Pull request by mwu-tow**
As discussed in issue #52 I made an attempt to add support for lambda-expressions. I tested current code and it seems to cover all needs of AccelerateHS/accelerate-cuda package. That covers expressions like `[&]{ int a = 3; return x[a]; }()`.

As we have no need to provide complete support for parsing and printing C++11 lambdas I think it would be right to stop at the current feature-set, if only it is properly documented.

**Current limitations:**
* only [] [=] [&] are supported as the lambda-introducers (it is not possible to specify capture mode for indivdual variables), not to speak of C++14 goodness
* no support for specifying arguments list — lambdas will by default take zero arguments
* no support for specifying return type — it will be deduced from the return statement (or void if there is no return)

**I have several doubts as for the implementation:**
* where should parser rules like `capture_list` be placed? I put them right under the expression rule that uses it but I'm not sure if this is right
* please check if I got the naming conventions right
* I added lambdas to the `primary_expression` rule. There is also `primary_expression_nlt` rule that seems relevant — should I just duplicate my code and put it at `primary_expression_nlt` as well?
* where should I place the documentation about what is and what is not supported for lambdas?

Thank you for your help!

### CODE REVIEW

**Comment by mwu-tow** [comment]
I have updated the pull request:
* I have added support for parsing the parameters list.
* parameter list can be followed by `mutable` identifier. The `mutable` is treated as keyword wheen CUDA extensions are enabled.
* I did some renames to use more standardeese terminology.
* I added lambdas to the `_nlt` variant of `primary_expression` as well.

Currently lambdas support has the following limitations:
* only `[]`, `[&]` and `[=]` work as a lambda introducers
* the returned type cannot be explicitly specified (it will be deduced from return expression)
* obviously lambdas and their parameters syntax are limited to C language (so `(const std::string &s)` as a parameter won't parse)

I have tried to add support for explicit stating return type but I the naive approach creates conflicts in grammar, so I gave up. If anyone is interested in fixing this, please take a look at a commented-out part of the `cuda_lambda_return_type` rule in `Parser.y`. At the moment I have no plans to fix neither of remaining issues — their value is limited. The primary use-case for this PR — that is using lambda-expressions in kernels generated by `accelerate-cuda` — is fulfilled. 

@mainland  Please take a look at the proposed changes and let me know if something more is needed before this PR can go through. 

I have a fork of `accelerate-cuda` that uses this version of `language-c-quote` to generate kernels with lambdas and it is confirmed that this solves problem with running kernels on Windows and using the NVRTC. (see https://github.com/mwu-tow/accelerate-cuda/tree/lambda-expressions and discussion in https://github.com/AccelerateHS/accelerate/issues/234 and https://github.com/AccelerateHS/accelerate/issues/258 ). 
This is the last big blocker for having `accelerate-cuda` run on Windows.

**Comment by mwu-tow** [comment]
I have added tests checking whether lambdas are properly parsed.

**Comment by mainland** [comment]
I certainly appreciate the work you've put into this patch. Thank you!

However, I am conflicted about how to proceed. This is a substantial change, which imposes some ongoing maintenance cost, essentially just to support Accelerate on Windows.

While the implementation of lambda expressions is more than the minimum necessary for Accelerate, it is necessarily incomplete and it is not clear whether or not there are other (non-hypothetical) use cases besides Accelerate support on Windows.

Regarding Accelerate support on Windows, there are two other solutions I can think of that would not require a large patch to an external package. Really, the problem is with Accelerate ;)

1. Fix the code generator. Having written a number of C code generators in the past, I have always lowered code so that statement expressions are not necessary. I understand this might be a decent amount of work.
1. A simpler hack is to post-process the code output by Accelerate's code generator: treat it as a string and substitute `({` and `)}` with appropriate strings to yield lambda expressions. This seems like *much* less work than patching `language-c-quote`. Did anyone try it? We've done something similar in GHC's LLVM back end before; yes it's a hack, but sometimes that the most expedient solution.

**Comment by mwu-tow** [comment]
Thank you for finding the time to review the changes despite your busy schedule.

This change is relatively small, localized, well-defined and covered with tests. It only brings support for lambdas, so no existing correct code will be broken. It works only with CUDA extensions so the impact will be quite contained. 
Of course, there is no code that does not impose some kind of maintenance cost. Yet, I think that the cost in this case is much lower then the brought value. In your eyes it may be "just to" support Accelerate on Windows but for us that support is a must-have requirement. That single use-case is enough for us to maintain the fork with change. Having it merged upstream is now rather about reducing the maintenance cost and making the Accelerate library accessible to normal Windows users that do not posses arcane knowledge about my forks.

I hope that accepting this pull request won't bring you much maintenance trouble — and in any case I'd be always happy to help. As I said — I will have to maintain it anyway.

As for your another points — you question whether this is something that should be solved on the `language-c-quote` side at all if sufficient workarounds are possible on the `accelerate-cuda` side. 

Well, perhaps if you'd said that a few months earlier I'd give more attention to the possible workarounds but even now I think that supporting lambdas in your library is the best possible approach.
Rewriting `accelerate-cuda` so it doesn't use statement expressions is technically possible but this approach is difficult and bug-prone. And, what I find perhaps even more important, I don't think it is right — why should we obfuscate code generator and suffer from workarounds if the CUDA compiler supports the language feature that neatly solves the problem at hand? Realistically we can't have full lambdas (and rest of C++) support but it is not a reason to keep a useful feature unavailable to users of your package.

**Comment by mchakravarty** [comment]
@mainland I just looked over the patches and they do look clean and self-contained.

While I fully understand your concerns, I personally would be in favour of including them into `language-c-quote`. My reasons are as follows:

* Removing the use of statement expressions in Accelerate is indeed not that easy and it would make debugging the Accelerate-generated code substantially harder. As you are saying, these are no insurmountable problems, but the required changes would be much more substantial than the patches under consideration here.
* Post processing the Accelerate code would also require substantial changes to Accelerate as the code is not compiled by an offline compilation process, but on demand by Accelerate itself and we currently have no facilities for a post processing step like that.
* Given (1) that @mwu-tow has demonstrated that he knows what he is doing, (2) that he offered to help maintain the code, and (3) that the changes are isolated and fairly small, I'd not be too worried about maintenance — especially, as we'll need to keep them working to keep Accelerate working on Windows. (I'd be much more worried about an addition that might not be used much, but this one is going to be exercised on a regular basis.)

Finally, I'd like to say, that given nobody on the Accelerate team uses Windows, we have always struggled with Windows support. Hence, I am very grateful to @mwu-tow for taking the initiative here.

**Comment by mainland** [comment]
OK, noted. To clarify, I was suggesting that when the C code is converted to a string, statement expression brackets be converted to lambda expressions. Presumably there is a string of C code generated somewhere before it is passed to the compiler...are you saying that performing a search and replace on that string would require substantial changes to Accelerate?

Also, the patch in its current form cannot be automatically merged.

**Comment by mwu-tow** [comment]
I have merged your recent changes so that patch can be merged automatically. Let me know if there is something that I can improve in my patch to make you think of it more like "neat extension" rather than "loathsome grammar hack". 

As for whether implementing a regexp-based hack on the side of `accelerate-cuda` would be much smaller or neater solution, someone with better knowledge on the subject should speak up. ( @mchakravarty @tmcdonell ) I'm somewhat afraid that reliably finding where the last expression in the code block begins (in order to place return before it) might be non-trivial.

**Comment by mchakravarty** [comment]
@tmcdonell What do you think about this?

**Comment by tmcdonell** [comment]
The motivation for introducing statement expressions, which are relatively recent, is to ensure logical operators short circuit correctly. The proposed `substituteForStatementExpressions` would be far from minor surgery in this case.

I think that, if this was going to happen in `accelerate-cuda`, then the entire code generator would need to be rewritten from something that generates C expressions to something that generates C statements. This is why statement expressions were such an elegant solution for us. You could argue that that is really The Right Way to do it, but that is a vastly more significant undertaking, and I can't see anywhere in the foreseeable future where I'd get a chance to do that. I think @mwu-tow has a reasonable compromise in this patch.

**Comment by mainland** [comment]
The proposal in question was a regexp substitution to substitute lambda expressions for statement expressions in the string representation of the generated code, not a rewrite of the code generator :) Is such a thing doable?

**Comment by tmcdonell** [comment]
Ah, I see what you mean now. Hm, well, I am suspicious of such stringy code-generation (this is why I moved over to `language-c-quote`!), but I guess with string munging anything is possible, right? (-; If nothing else, we'd lose the guarantee that the generated code is at least syntactically valid.

I can not comment on whether it would be simple and maintainable though, as my regex-fu is not strong.

**Comment by mainland** [comment]
OK, I will merge this, but please tidy up the commits so that the merge history will concisely show what exactly has changed. In particular, please rebase instead of adding a non-empty merge commit. If you want to squash everything to a single commit, that should be fine.

**Comment by mwu-tow** [comment]
Done, I have squashed everything into a single commit. Please let me know if it is all right now.

**Comment by mainland** [comment]
Merged, thanks!

**Pull request closed without merging**
